name             'berks-fuck-you'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures berks-fuck-you'
long_description 'Installs/Configures berks-fuck-you'
version          '0.1.0'
